### ISSUE TITLE
Roadmap v5.0.0

### ISSUE THREAD

**Issue by cyrildewit** [cyrildewit/eloquent-viewable#170]
There were some issues in version 3 which I fixed in `v4.0.0`, but while working on the fixes I came up with some ideas to make a change to the underlying logic and design. I decided to only do the minimal required changes to fix these issues and refactor it in `v5.0.0`, so it wouldn't take to long to get to a stable release. Since there was a serious bug in `v3`.

### Core

- [x] Remove deprecated methods
- [x] Can the visitor's data be extracted into its own class? `Visitor`? Which holds the session id, cookie id, IP address, etc. (#171)
- [x] Remove the `countByType` method and put it's logic under the `count` method (keep the destroy method in mind)
- [x] Redesign session delay functionality.
- [x] Look for better integration in Eloquent (eager loading?, withCount?)
- [x] Remove `HeaderResolver`
- [x] Remove `IpAddressResolver`
- [x] Maybe `withViewsCount()` method in `Viewable` trait as a wrapper to withCount but with support for unique, period and collection.
- [x] Revisit Period class (especially types)
- [x] Revisit Views class (especially types)
- [x] Replace usages of `app()` helper with `Container::getInstance()`
- [x] Replace usages of `config()` helper with `Container::getInstance()`
- [x] Add ability to set `viewer` object in `Views` class
- [x] Learn more about context objecs and determine if it's useful for the Viewer class.
- [x] Ability to overwrite cooldown method (callable? as second parameter)

### Dependencies

- [x] Bump minimum version to PHP 7.2 and up
- [x] Drop support for Laravel 5.8
- [x] Add support for Laravel 6
- [x] Add support for Laravel 7

### Tests

- [x] Test `Period::sub` for Exception
- [x] Test `Views::resolveCacheLifeTime` for instance of DateTimeInterface
- [x] Test `Views::resolveCacheLifeTime` for instance of CarbonInterface
- [x] Test `Views::resolveCacheLifeTime` for int

### Other

- [x] Switch from TravisCI to GitHub Actions

### Documentation

- [x] Rewrite section about caching (remove tutorial like lines and get to the point fast)
- [x] Add section about optimizations in readme
  - Table indexes ($table->string('visitor')->nullable()->change(); $table->index(['visitor']);)
  - Caching
- [ ] Add section with benchmarks

---

- ~Think if renaming the methods: `period`, `collection` and `unique` to something more like this: `withinPeriod`, `withinCollection` and `onlyUnique` is a good idea.~
- ~Split logic in the `shouldRecord` method into multiple functions which can be overridden independently~
- ~Refactor the creation of the `View` object within the `record` method into its own method~
- ~Refactor `VisitorCookieRepository`: move logic into `Viewer` class and use `request()` method to retrieve/store the cookie~

**Comment by cyrildewit** [comment]
### Redesign session delay

- [ ] Rename it to cooldown

**Comment by cyrildewit** [comment]
## Viewer class implementation

The `Viewer` class represents the current viewer and holds data like request information (session), cookies, IP Address, etc. Somethin like a context object.

The current `Views` class contains the following logic:

- `protected function resolveIpAddress()`: Resolves the visitor's IP address.
- 'protected function requestHasDoNotTrackHeader()': Determines if the request has the `HTTP_DNT` header.
- `protected function resolveVisitorId()`: Resolves the unique ID that's given to a visitor using a cookie.

All these methods could be moved to the `Viewer` class.

**Comment by cyrildewit** [comment]
## Removal of `countByType` method

Both `count` and `countByType` are very similar. The only difference is the cache key generation and base query. By removing some flexibility, we can accommodate the `countByType` functionality under the `count` method.

The current `countByType` method accepts a 'viewable type' as the first argument, but since this argument doesn't belong to the `count` method. We need to find another way.

We could accept it as the first value in the `views()` function.

```php
views(Post::class); // viewable type is given like this
```

The function inner workings would then look like this:

```php
function views($viewable = null)
{
    if (is_string($viewable)) {
        return app(Views::class)-forViewableType($viewable);
    }

    return app(Views::class)->forViewable($viewable);
}
```

One drawback is that we can't set the viewable type to null, because we only check if it's null. Another check could reset both of them?

**Comment by cyrildewit** [comment]
## Rename setters in `Views` class

- Rename `period(...)` to `withinPeriod(...)`
- Rename `collection(...)` to `withinCollection(...)`
- Rename `unique(...)` to `onlyUnique(...)` or `hasUniqueVisitors(...)`

Example:

```php
views($post)
    ->withinPeriod(Period::pastDays(2))
    ->withinCollection('')
    ->onlyUnique()
    ->count();

views($post)
    ->withinPeriod(Period::pastDays(2))
    ->withinCollection('')
    ->hasUniqueVisitors()
    ->count();
```

**Comment by cyrildewit** [comment]
# Eloquent database queries improvement

## Tasks

* [ ] Do some benchmarks for all the possible queries

**Comment by francoism90** [comment]
In V4 I used the `overrideVisitor` method to have an exact userID, it seems this method has been removed in V5. Not a big problem, I do not use this in production. I was just wondering if it possible to extract the user info when using the default `visitor` value, I do plan to use it in some queries, like if the user has seen a model before. Thanks!
