### ISSUE TITLE
Roadmap v6.0.0

### ISSUE THREAD

**Issue by cyrildewit** [cyrildewit/eloquent-viewable#212]
## Core

* [x] Dispatch `ViewRecorded` event when a view is recorded.
* [x] Subtract creation of view into `createView` method from the `record` method to make extending this functionality easier.
* [x] Add throws docblocks.
* [x] Create `ViewRecordException`.
*  ~Solution to use the cooldown functionality in Jobs~
    * Related issues: #164
* ~Extra properties (meta data) #218~ 
* [x] Fix behavior described in #241 
* [x] Look into a cleaner run-test workflow
* [x] Bump minimum PHP version to 7.4
* [x] Add support for PHP 8
